#!/usr/bin/env python3
"""Independently compare stock tap CDL/SPICE intent with the public PCell formula."""
import argparse,hashlib,json,math,re,shutil
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(exist_ok=False);shutil.copyfile(Path(__file__),a.output/'runner.py');root=Path(__file__).resolve().parents[4];pdk=Path('/foss/pdks/ihp-sg13g2')
files={'geometry_audit':root/'designs/g1-guardian/review/audits/io-tap-geometry-20260921.json','tech':pdk/'libs.tech/klayout/python/sg13g2_pycell_lib/sg13g2_tech.json','utility':pdk/'libs.tech/klayout/python/sg13g2_pycell_lib/ihp/utility_functions.py','pcell':pdk/'libs.tech/klayout/python/sg13g2_pycell_lib/ihp/ptap1_code.py','cdl':pdk/'libs.ref/sg13g2_io/cdl/sg13g2_io.cdl','spice':pdk/'libs.ref/sg13g2_io/spice/sg13g2_io.spi','electrical_model':pdk/'libs.tech/ngspice/models/resistors_mod.lib','tap_extraction':pdk/'libs.tech/klayout/tech/lvs/rule_decks/tap_extraction.lvs'}
texts={k:f.read_text(errors='replace') for k,f in files.items()};g=json.loads(texts['geometry_audit']);assert hashlib.sha256(files['cdl'].read_bytes()).hexdigest()==g['cdl_sha256']
def number(s):
 m=re.fullmatch(r'([-+0-9.eE]+)([a-zA-Z]*)',s);return float(m[1])*{'':1,'m':1e-3,'u':1e-6,'n':1e-9,'p':1e-12,'f':1e-15,'k':1e3}[m[2].lower()]
raspec=number(re.search(r'"ptap1_raspec":\s*"([^"]+)"',texts['tech'])[1])*1e12;rpspec=number(re.search(r'"ptap1_rpspec":\s*"([^"]+)"',texts['tech'])[1])*1e6
formula=texts['utility'].split('def CbTapCalc',1)[1].split('return result',1)[0];assert 'result = 1.0/(1.0/(raspec/a) + 1.0/(rpspec/p))' in formula
rows=[]
for r in g['rows']:
 body=re.search(r'(?ims)^\.subckt '+r['cell']+r'\b(.*?)^\.ends',texts['spice'])[1];line=next(x for x in body.splitlines() if 'ptap1' in x);rs=number(re.search(r'\bR=(\S+)',line)[1]);ac,pc=r['cdl_area_um2'],r['cdl_perimeter_um'];ag,pg=r['geometry_area_um2'],r['geometry_perimeter_um'];rc=1/(ac/raspec+pc/rpspec);rg=1/(ag/raspec+pg/rpspec)
 rows.append({'cell':r['cell'],'stock_spice':line,'stock_R_ohm':rs,'stock_CDL_A_um2':ac,'stock_CDL_P_um':pc,'CDL_formula_R_ohm':rc,'CDL_formula_relative_to_stock_error':rc/rs-1,'raw_geometry_A_um2':ag,'raw_geometry_P_um':pg,'geometry_formula_R_ohm_conditional':rg,'stock_over_geometry_formula_R':rs/rg,'square_perimeter_relative_error':pc/(4*math.sqrt(ac))-1})
result={'scope':'Read-only independent PCell/reference semantic audit; not electrical validation of arbitrary guard-ring geometry, not schematic rewrite, no LVS closure.','pdk_commit':(pdk/'COMMIT').read_text().strip(),'inputs':{k:{'path':str(f.relative_to(root)) if f.is_relative_to(root) else str(f.relative_to(pdk)),'sha256':hashlib.sha256(f.read_bytes()).hexdigest()} for k,f in files.items()},'formula':'R=1/(A/raspec+P/rpspec), with A inum²,P inum; publicCbTapCalc function','raspec_ohm_um2':raspec,'rpspec_ohm_um':rpspec,'rows':rows,'CDL_SPICE_same_equivalent_square_model':'passed' if max(abs(r['CDL_formula_relative_to_stock_error']) for r in rows)<.001 else 'failed','geometry_electrical_model_validity':'not run: applying rectangle-PCell A/P equation to arbitrary guard rings is a conditional inference','full_IO_LVS':'failed; unchanged prior result'}
(a.output/'summary.json').write_text(json.dumps(result,indent=2)+'\n');(a.output/'CbTapCalc_excerpt.txt').write_text('def CbTapCalc'+formula+'return result\n');(a.output/'ptap1_model_excerpt.txt').write_text(re.search(r'(?ims)^\.subckt ptap1\b.*?^\.ends ptap1',texts['electrical_model'])[0]+'\n');print(json.dumps(result,indent=2))
