// Auto-generated by LibreLane
module g1_digital(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input osc_clk,
  input por_n,
  input en,
  input sclk,
  input sdi,
  output sdo,
  output cmp_clk,
  input cmp_soft,
  input cmp_hard,
  output[7:0] dac_soft,
  output[7:0] dac_hard,
  output trip_set_sel,
  output trip_d,
  output clr_d,
  output fast_en,
  input tripped,
  output trip,
  output gate_en,
  output fault_n,
  output[1:0] trip_cause,
  output osc_en,
  output[3:0] osc_trim,
  output t2f_en,
  output t2f_mode,
  output bgr_r4,
  output clk_div_out
);
endmodule
