#!/usr/bin/env python3
"""Write ../layout/PINS.md, the pin table of the g1_digital macro of record, from its LEF.

Geometry (layer, edge, coordinates) is read from the LEF so it is never hand
transcribed; direction, domain and destination come from the table below, which
follows G1_REGISTER_MAP.md section 2, blocks/g1_trip/INTERFACE.md and
blocks/g1_t2f/INTERFACE.md. Re-run after every LibreLane run that changes the
macro of record:  pins_md.py <g1_digital.lef> <run tag> <lef sha256> > ../layout/PINS.md
"""
import re
import sys

lef_path, tag, sha = sys.argv[1], sys.argv[2], sys.argv[3]

# name -> (domain, destination, note); bus names without the index
SIGNALS = {
    "osc_clk":      ("1.2 V", "G1_OSC",                 "system clock ~10 MHz, in"),
    "osc_en":       ("1.2 V", "G1_OSC",                 "1 = oscillator runs (reset 1)"),
    "osc_trim":     ("1.2 V", "G1_OSC",                 "capacitor trim, code 8 nominal"),
    "por_n":        ("1.2 V", "analog wrapper (POR)",   "power-on reset, active low; tie to VDD if no POR cell exists"),
    "en":           ("1.2 V", "`EN` pad 12 (`p2c`)",    "`en_core`; low resets the core"),
    "sclk":         ("1.2 V", "`SCLK` pad 14 (`p2c`)",  "serial clock"),
    "sdi":          ("1.2 V", "`SDI` pad 15 (`p2c`)",   "serial data in"),
    "sdo":          ("1.2 V", "`SDO` pad 16 (`c2p`)",   "serial data out"),
    "cmp_clk":      ("1.2 V", "G1_TRIP",                "comparator strobe = osc_clk/2"),
    "cmp_soft":     ("1.2 V", "G1_TRIP (soft comparator)", "asynchronous, synchronised inside"),
    "cmp_hard":     ("1.2 V", "G1_TRIP (hard comparator)", "asynchronous, synchronised inside; also feeds the G1_GATE fast path"),
    "dac_soft":     ("1.2 V", "G1_TRIP (soft DAC)",     "effective code, static"),
    "dac_hard":     ("1.2 V", "G1_TRIP (hard DAC)",     "effective code, static"),
    "trip_set_sel": ("1.2 V", "G1_TRIP",                "1 = hard reference from the `TRIP_SET` pad"),
    "trip_d":       ("1.2 V", "G1_GATE",                "level, sets the 3.3 V latch"),
    "clr_d":        ("1.2 V", "G1_GATE",                "200 ns pulse, clears the latch"),
    "fast_en":      ("1.2 V", "G1_GATE",                "enables the analog fast path (reset 0)"),
    "tripped":      ("1.2 V", "G1_GATE",                "latch state, asynchronous, synchronised inside"),
    "trip":         ("1.2 V", "test / monitor, else open", "digital latch state (the `GATE` / `FAULT_N` pads are driven by G1_GATE)"),
    "gate_en":      ("1.2 V", "test / monitor, else open", "`en & ~trip`"),
    "fault_n":      ("1.2 V", "test / monitor, else open", "`~trip`"),
    "trip_cause":   ("1.2 V", "test / monitor, else open", "0 none, 1 soft, 2 hard, 3 forced"),
    "t2f_en":       ("1.2 V", "`g1_ls_up` -> `g1_t2f.en` (3.3 V)",   "`TEMP_CTRL.T2F_EN`, reset 1"),
    "t2f_mode":     ("1.2 V", "`g1_ls_up` -> `g1_t2f.mode` (3.3 V)", "`TEMP_CTRL.T2F_MODE`, reset 0"),
    "bgr_r4":       ("1.2 V", "`g1_ls_up` -> `g1_bgr.r4` (3.3 V)",   "`TEMP_CTRL.BGR_R4`, reset 0"),
    "clk_div_out":  ("1.2 V", "optional test mux, else open", "osc_clk / 2^(9+OSC_DIV)"),
    "VDD":          ("1.2 V", "core PDN",                "TopMetal1 vertical + TopMetal2 horizontal stripes"),
    "VSS":          ("0 V",   "core PDN",                "TopMetal1 vertical + TopMetal2 horizontal stripes"),
}

lef = open(lef_path).read()
size = re.search(r"SIZE\s+([\d.]+)\s+BY\s+([\d.]+)", lef)
W, H = float(size.group(1)), float(size.group(2))
pins = re.findall(r"PIN (\S+)\s+(.*?)END \1", lef, re.S)


def edge_of(x1, y1, x2, y2):
    if y2 >= H - 0.5: return "N"
    if y1 <= 0.5: return "S"
    if x2 >= W - 0.5: return "E"
    if x1 <= 0.5: return "W"
    return "-"


rows, power = [], []
for name, body in pins:
    d = re.search(r"DIRECTION (\w+)", body).group(1)
    use = re.search(r"USE (\w+)", body)
    use = use.group(1) if use else "SIGNAL"
    rects = []
    for layer, block in re.findall(r"LAYER (\S+) ;((?:\s*RECT[^;]*;)+)", body):
        for r in re.findall(r"RECT ([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+)", block):
            rects.append((layer, tuple(float(v) for v in r)))
    base = re.sub(r"\[\d+\]$", "", name)
    dom, dest, note = SIGNALS[base]
    if use in ("POWER", "GROUND"):
        power.append((name, d, use, rects, dom, dest, note))
    else:
        layer, (x1, y1, x2, y2) = rects[0]
        rows.append((name, d, dom, dest, note, layer, edge_of(x1, y1, x2, y2), x1, y1, x2, y2))

# order: by edge then position along the edge
order = {"N": 0, "E": 1, "S": 2, "W": 3, "-": 4}
rows.sort(key=lambda r: (order[r[6]], r[7] if r[6] in "NS" else r[8]))

out = []
out.append(f"# g1_digital macro pins ({tag})\n")
out.append(f"Pin table of the `g1_digital` macro of record (LibreLane run tag `{tag}`, `../reports/librelane_{tag}/`), "
           f"generated by `../flow/pins_md.py` from `g1_digital.lef` (sha256 `{sha[:16]}…`). "
           f"Macro size {W:g} × {H:g} µm, origin at the lower-left corner; coordinates in µm. "
           "Every signal pin is 1.2 V CMOS (`sg13g2_stdcell`, `VDD`/`VSS`); the only signals that "
           "continue into the 3.3 V domain do so through one `g1_ls_up` cell each (`../ls/`). "
           "Direction is from the macro's point of view. Destinations follow "
           "`../../../specification/G1_REGISTER_MAP.md` section 2 and the two `INTERFACE.md` files.\n")
out.append(f"Signal pins: {len(rows)}; power pins: {len(power)} (`VDD`, `VSS`). "
           "Signal pins sit on the macro boundary (0.4 µm wide): north-edge pins on Metal2 (vertical access), "
           "east/west-edge pins on Metal3 (horizontal access). The pin placer chose the edges freely "
           "(no `FP_PIN_ORDER_CFG`); if the chip floorplan wants a different assignment, add a pin-order "
           "file to `../flow/config.yaml` and re-run the flow, gate-level simulation and signoff.\n")
out.append("| Pin | Dir | Domain | To / from | Layer | Edge | x1 | y1 | x2 | y2 | Note |")
out.append("| --- | --- | --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- |")
for name, d, dom, dest, note, layer, edge, x1, y1, x2, y2 in rows:
    out.append(f"| `{name}` | {d.lower()} | {dom} | {dest} | {layer} | {edge} | {x1:.2f} | {y1:.2f} | {x2:.2f} | {y2:.2f} | {note} |")
out.append("")
out.append("## Power pins\n")
out.append("| Pin | Use | Layer | Stripes (x1 y1 x2 y2) |")
out.append("| --- | --- | --- | --- |")
for name, d, use, rects, dom, dest, note in power:
    by_layer = {}
    for layer, r in rects:
        by_layer.setdefault(layer, []).append(r)
    for layer, rs in by_layer.items():
        rs.sort()
        cells = "; ".join(f"{a:.2f} {b:.2f} {c:.2f} {e:.2f}" for a, b, c, e in rs)
        out.append(f"| `{name}` | {use} | {layer} | {len(rs)}: {cells} |")
out.append("")
out.append("Both nets are 1.2 V core supply/ground (`VDD` / `VSS` pads 1, 7 / 2, 5). The stripes are on the "
           "PDK PDN pitch, so the chip stripes cross them and `PDN_MACRO_CONNECTIONS: [\"i_core.<inst> VDD VSS VDD VSS\"]` "
           "connects them without a custom PDN configuration (`../../g1_padring/INTEGRATION.md`, dry run with the run4 macro).\n")
out.append("## Connections summary by block\n")
groups = {}
for name, d, dom, dest, note, *_ in rows:
    key = re.sub(r"\s*\(.*", "", dest)
    groups.setdefault(key, []).append(f"`{name}`")
def natural(n):
    m = re.match(r"`(\w+)(?:\[(\d+)\])?`", n)
    return (m.group(1), int(m.group(2) or 0))
for key, names in groups.items():
    out.append(f"- **{key}**: {', '.join(sorted(names, key=natural))}")
out.append("")
out.append("Chip-level timing constraints for this macro (clock definitions on `osc_clk`/`SCLK`, uncertainties, false paths, IO delays) are in `g1_digital_top.sdc`, with the rationale and the re-run of the dry-run STA in `TOP_SDC.md`.\n")
out.append("The three 3.3 V-bound control bits need three `g1_ls_up` instances (`../ls/README.md`); no other pin leaves the 1.2 V domain. "
           "`en` is the pad-level-shifted `EN` (`p2c` of `sg13g2_IOPadIn`, 1.2 V), shared with G1_GATE. "
           "`osc_clk` is the only clock input besides `sclk`; both are declared asynchronous in `../flow/g1_digital.sdc`.")
print("\n".join(out))
