#!/usr/bin/env bash
# g1_ls_up simulations (ngspice 46 in the pinned container).
# Usage (repo root): G1_WORKDIR=designs/g1-guardian/blocks/g1_ctrl/ls/sim flow/run.sh bash run_ls.sh <what>
#   sweep   81 points: mos {tt,ff,ss} x vdd {1.08,1.2,1.32} x vdda {2.97,3.3,3.63} x temp {-40,27,175}
#           -> logs/sweep.log (RES lines + ngspice errors), results_ls.txt (table)
#   pwr     power-up order A/D and vdd-absent case at mos tt/ss/ff -> logs/pwr.log, appended to results_ls.txt
#   all     both
# Decks are instantiated from tb_ls.cir / tb_ls_pwr.cir into build/g1_ls/sim (gitignored).
set -u
B=../../../../../../build/g1_ls/sim
mkdir -p logs "$B"
hdr() { echo "# $1  $(date -u +%FT%H:%MZ)  $(ngspice -v 2>/dev/null | grep -m1 -o 'ngspice-[0-9]*')  PDK $(cat /foss/pdks/ihp-sg13g2/COMMIT 2>/dev/null | cut -c1-7)"; }
sweep() {
  hdr "g1_ls_up corner sweep: tb_ls.cir, 1.2 V step, 20 fF load; delays 50 % in -> 50 % out" > logs/sweep.log
  for mos in mos_tt mos_ff mos_ss; do for vdd in 1.08 1.2 1.32; do for vdda in 2.97 3.3 3.63; do for t in -40 27 175; do
    tag="ls_${mos}_${vdd}V_${vdda}V_${t}C"
    sed -e "s/@@MOS@@/$mos/g" -e "s/@@VDD@@/$vdd/g" -e "s/@@VDDA@@/$vdda/g" -e "s/@@TEMP@@/$t/g" tb_ls.cir > "$B/$tag.cir"
    ngspice -b "$B/$tag.cir" > "$B/$tag.log" 2>&1
    grep -E "^RES|^Error|rror:|Timestep too small|failed" "$B/$tag.log" >> logs/sweep.log
  done; done; done; done
}
pwr() {
  hdr "g1_ls_up power-up: tb_ls_pwr.cir, in = 0 during the ramps, 27 C" > logs/pwr.log
  for mos in mos_tt mos_ss mos_ff; do for order in A D; do
    if [ $order = A ]; then PA="0 0 0.5u 0 1.5u 3.3 9u 3.3 12u 3.3"; PD="0 0 3u 0 4u 1.2 9u 1.2 9.5u 0 12u 0"
    else                   PD="0 0 0.5u 0 1.5u 1.2 9u 1.2 9.5u 0 12u 0"; PA="0 0 3u 0 4u 3.3 9u 3.3 12u 3.3"; fi
    tag="ls_pwr_${mos}_$order"
    sed -e "s/@@MOS@@/$mos/g" -e "s/@@ORDER@@/$order/g" -e "s/@@PWLA@@/$PA/" -e "s/@@PWLD@@/$PD/" tb_ls_pwr.cir > "$B/$tag.cir"
    ngspice -b "$B/$tag.cir" > "$B/$tag.log" 2>&1
    grep -E "^POWERUP|^Error|rror:|Timestep too small|failed" "$B/$tag.log" >> logs/pwr.log
  done; done
}
summarise() {
  {
    echo "# g1_ls_up simulated results (ngspice 46, PDK commit 8437402), generated by run_ls.sh $(date -u +%FT%H:%MZ)"
    echo "# corner sweep: in 0->1.2 V step (1 ns edge), vdd/vdda as listed, 20 fF on out; tr/tf = 50 % in -> 50 % out"
    printf "%-7s %-5s %-5s %-5s %8s %8s %7s %7s %10s %10s %10s %10s %8s\n" mos vdd vdda T tr_ps tf_ps vh_V vl_V Ia0_nA Ia1_nA Ic0_nA Ic1_nA Iapk_uA
    grep "^RES" logs/sweep.log | awk '{printf "%-7s %-5s %-5s %-5s %8.1f %8.1f %7.3f %7.4f %10.3f %10.3f %10.3f %10.3f %8.1f\n", $2,$3,$4,$5,$7,$9,$11,$13,$21,$22,$24,$25,$27}'
    echo
    echo "# summary over the sweep"
    grep "^RES" logs/sweep.log | awk '{tr=$7; tf=$9; if(NR==1||tr>mtr){mtr=tr;ctr=$2" "$3"/"$4" V "$5" C"} if(NR==1||tr<ntr){ntr=tr} if(NR==1||tf>mtf){mtf=tf;ctf=$2" "$3"/"$4" V "$5" C"} if(NR==1||tf<ntf){ntf=tf} if($11<0.9*$4||$13>0.1*$4) bad++; a=$21; if(a<0)a=-a; if(a>ma){ma=a;ca=$2" "$5" C"} a=$22; if(a<0)a=-a; if(a>ma){ma=a;ca=$2" "$5" C"}} END{printf "points=%d  tr min/max = %.0f / %.0f ps (max at %s)  tf min/max = %.0f / %.0f ps (max at %s)  points with |out swing| outside 10..90 %% of vdda: %d  max |Ivdda static| = %.3f nA (%s)\n", NR, ntr, mtr, ctr, ntf, mtf, ctf, bad+0, ma, ca}'
    grep -c "^RES" logs/sweep.log | sed 's/^/# RES lines: /'
    grep -v "^RES\|^#" logs/sweep.log | sed 's/^/# ngspice message: /'
    echo
    echo "# power-up (tb_ls_pwr.cir, 27 C): order A = vdda ramps 0.5-1.5 us then vdd 3-4 us; D = vdd first; in = 0 until a 1.2 V pulse at 6-7 us; vdd removed at 9-9.5 us"
    grep "^POWERUP" logs/pwr.log
    grep -v "^POWERUP\|^#" logs/pwr.log | sed 's/^/# ngspice message: /'
  } > results_ls.txt
  cat results_ls.txt
}
case ${1:-all} in
  sweep) sweep; summarise ;;
  pwr) pwr; summarise ;;
  all) sweep; pwr; summarise ;;
  sum) summarise ;;
esac
