#!/usr/bin/env python3
"""Turn the kpex (KLayout-PEX 0.3.12, 2.5D engine, --mode CC) SPICE output into an ngspice
subcircuit with the schematic's port names, so that a testbench can .include it in place of the
xschem netlist.

  python3 make_pex_netlist.py trip|osc <kpex .spice> <out .spice>

Edits (format and the two documented layout-vs-extraction fixes, no other circuit content):
- device instances become subcircuit calls of the PDK models: M$n -> XMn (kpex writes D G S B),
  R$n -> XRn; "$" is a comment character for ngspice;
- MOS parameters W/L get a "u" suffix (kpex writes W=4U); AS/AD/PS/PD/rfmode are dropped (the
  xschem netlist passes w, l, ng, m only);
- trip: the PEX input had the ThickGateOx layer removed (kpex 0.3.12 stops with KeyError '<TODO>'
  on it, see layout/pex_input.py), so the thick-oxide devices extract as sg13_lv_*; every device
  with L = 0.45 um is a 3.3 V device in this block (LV lengths are 0.13 and 0.34 um) and gets its
  sg13_hv_* model back;
- the cmim capacitors were removed from the PEX input for the same reason; they are re-inserted
  here as the schematic cap_cmim devices between the extracted net names (layout labels);
- resistors: "R$n a b sub 1 rppd l=58.5 ps=0 b=0 m=1" -> "XRn a b sub rppd w=1u l=58.5u b=0 m=1";
- parasitic capacitors Cext_n keep their values (a/f suffixes are ngspice units); node names
  "\\$12" -> "n12"; the substrate node VSUBS is the vss net;
- the subcircuit port list is reduced to the schematic pins, renamed from the macro pin names
  (ISENSE -> isense, dac_soft[0] -> soft0, IOVDD -> vdda, ...), in the schematic order;
- the PEX input is the flattened layout, so a net carries every label it has (top pin, sub-cell
  pin label, our internal label) joined by '|' (e.g. `inn|out|vth_soft`, `clk|cmp_clk_n`); the
  internal label wins, then the top-level pin name, else the first name.
"""
import re
import sys

CFG = {
    'trip': {
        'ports': ['isense', 'vref', 'cmp_clk'] + ['soft%d' % b for b in range(8)] + ['hard%d' % b for b in range(8)]
                 + ['cmp_soft', 'cmp_hard', 'vdd', 'vdda', 'vss'],
        'rename': dict([('ISENSE', 'isense'), ('VREF', 'vref'), ('clk', 'cmp_clk'), ('VDD', 'vdd'), ('IOVDD', 'vdda'),
                        ('VSS', 'vss'), ('VSUBS', 'vss')] + [('dac_soft[%d]' % b, 'soft%d' % b) for b in range(8)]
                       + [('dac_hard[%d]' % b, 'hard%d' % b) for b in range(8)]),
        'hv_l': 0.45,
        'caps': [('CHS', 'vth_soft', 'vss', 26.0), ('CHH', 'vth_hard', 'vss', 26.0), ('CH', 'icmp', 'vss', 26.0)],
    },
    'osc': {
        'ports': ['en', 'trim0', 'trim1', 'trim2', 'trim3', 'osc_clk', 'vdd', 'vss'],
        'rename': {'VDD': 'vdd', 'VSS': 'vss', 'VSUBS': 'vss', 'trim[0]': 'trim0', 'trim[1]': 'trim1',
                   'trim[2]': 'trim2', 'trim[3]': 'trim3'},
        'hv_l': None,
        'caps': [('CF_A', 'va', 'vss', 31.65), ('CT0_A', 'va', 'b0', 8.16), ('CT1_A', 'va', 'b1', 11.55),
                 ('CT2_A', 'va', 'b2', 16.33), ('CT3_A', 'va', 'b3', 23.09),
                 ('CF_B', 'vb', 'vss', 31.65), ('CT0_B', 'vb', 'bb0', 8.16), ('CT1_B', 'vb', 'bb1', 11.55),
                 ('CT2_B', 'vb', 'bb2', 16.33), ('CT3_B', 'vb', 'bb3', 23.09), ('CTH', 'vth', 'vss', 26.0)],
    },
}


def _si(v):
    """SPICE number with an optional scale suffix (kpex writes them in upper case: 0.6084P, 3.12U)"""
    m = re.match(r'([0-9.eE+-]+)([afpnumkAFPNUMK]?)', v)
    return float(m.group(1)) * {'a': 1e-18, 'f': 1e-15, 'p': 1e-12, 'n': 1e-9, 'u': 1e-6, 'm': 1e-3, 'k': 1e3, '': 1.0}[m.group(2).lower()]


def main():
    block, src, dst = sys.argv[1], sys.argv[2], sys.argv[3]
    cfg = CFG[block]
    ren = cfg['rename']
    lines = []
    for raw in open(src):
        raw = raw.rstrip('\n')
        if raw.startswith('+') and lines:
            lines[-1] += ' ' + raw[1:].strip()
        else:
            lines.append(raw)

    internal = set(a for _, a, b, _ in cfg['caps']) | set(b for _, a, b, _ in cfg['caps']) | {'cmp_clk_n', 'icmp'}

    def node(tok):
        # a flattened net carries every label it has (top pin, sub-cell pin, our internal label),
        # joined by '|': prefer our internal label, then the top-level pin name, else the first
        tok = tok.replace('\\', '')
        parts = tok.split('|')
        for x in parts:
            if x in internal and x not in ren:
                return x
        for x in parts:
            if x in ren:
                return ren[x]
        tok = parts[0]
        if tok.startswith('$'):
            return 'n' + tok[1:]
        return tok.replace('$', '_')

    out = ['* post-layout netlist of %s: kpex 2.5D CC parasitic capacitances, PDK devices from the layout' % block,
           '* generated by make_pex_netlist.py from %s (see its docstring)' % src.split('/')[-1],
           '.subckt %s %s' % ({'trip': 'g1_trip', 'osc': 'g1_osc'}[block], ' '.join(cfg['ports']))]
    nmos = nres = ncap = ndio = 0
    seen_subckt = False
    for ln in lines:
        s = ln.strip()
        if not s or s.startswith('*'):
            continue
        t = s.split()
        if t[0].upper() == '.SUBCKT':
            if seen_subckt:
                break          # kpex appends a second, empty .SUBCKT block
            seen_subckt = True
            continue
        if t[0].upper() == '.ENDS':
            continue
        if t[0].startswith('M'):
            name = 'XM' + t[0][2:]
            nets = [node(x) for x in t[1:5]]
            model = t[5]
            pd = dict(p.split('=', 1) for p in t[6:] if '=' in p)
            w = pd['W'].rstrip('Uu')
            l = pd['L'].rstrip('Uu')
            if cfg['hv_l'] is not None and abs(float(l) - cfg['hv_l']) < 1e-6:
                model = model.replace('sg13_lv_', 'sg13_hv_')
            out.append('%s %s %s w=%su l=%su ng=1 m=1' % (name, ' '.join(nets), model, w, l))
            nmos += 1
        elif t[0].startswith('R'):
            name = 'XR' + t[0][2:]
            nets = [node(x) for x in t[1:4]]
            w = t[4]
            model = t[5]
            pd = dict(p.split('=', 1) for p in t[6:] if '=' in p)
            out.append('%s %s %s w=%su l=%su b=%s m=%s' % (name, ' '.join(nets), model, w, pd['l'], pd.get('b', '0'), pd.get('m', '1')))
            nres += 1
        elif t[0].startswith('C'):
            nets = [node(x) for x in t[1:3]]
            out.append('%s %s %s %s' % (t[0].replace('$', '_'), nets[0], nets[1], t[3]))
            ncap += 1
        elif t[0].startswith('D'):
            # antenna diode (dantenna/dpantenna): kpex writes the extracted area A and perimeter P;
            # the PDK model takes w and l (A = w*l, P = 2(w+l))
            name = 'XD' + t[0][2:]
            nets = [node(x) for x in t[1:3]]
            model = t[3]
            pd = dict(p.split('=', 1) for p in t[4:] if '=' in p)
            a = _si(pd['A']) * 1e12          # um2
            per = _si(pd['P']) * 1e6         # um
            disc = max((per / 2) ** 2 - 4 * a, 0.0) ** 0.5
            w, l = (per / 2 + disc) / 2, (per / 2 - disc) / 2
            out.append('%s %s %s l=%.3gu w=%.3gu' % (name, ' '.join(nets), model, l, w))
            ndio += 1
        else:
            raise SystemExit('unhandled line: ' + s)
    for name, a, b, w in cfg['caps']:
        out.append('X%s %s %s cap_cmim w=%gu l=%gu m=1' % (name, a, b, w, w))
    out.append('.ends')
    open(dst, 'w').write('\n'.join(out) + '\n')
    print('wrote %s: %d MOS, %d resistors, %d diodes, %d parasitic capacitors, %d cmim re-inserted' % (dst, nmos, nres, ndio, ncap, len(cfg['caps'])))


if __name__ == '__main__':
    main()
