#!/usr/bin/env python3
"""Baseline BGR DC loading via actual AnalogPad and geometry-bounded routeR."""
import argparse,hashlib,json,math,os,re,shutil,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4];AUD=ROOT/'designs/g1-guardian/review/audits';BGR=ROOT/'designs/g1-guardian/blocks/g1_bgr/sim/qualification/runs/bgr_array_baseline_nominal_20260921_01';PDK=Path('/foss/pdks/ihp-sg13g2');sys.path.insert(0,str(ROOT/'designs/g1-guardian/blocks/g1_top/sim'))
from run_bounded import run_bounded
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--output',type=Path,required=True);a=p.parse_args();out=a.output.resolve();out.mkdir(exist_ok=False);shutil.copyfile(Path(__file__),out/'runner.py');base=BGR/'nominal.cir';pex=BGR/'pex_nominal.spice';geometry=AUD/'vref-route-geometry-20260922-r1.json';rc=AUD/'external-route-rc-estimates-20260921.json';tech=PDK/'libs.ref/sg13g2_stdcell/lef/sg13g2_tech.lef';g=json.loads(geometry.read_text());layer=json.loads(rc.read_text())['layers'];net=next(r for r in g['routes'] if r['net']=='i_core.vref');assert net['centerline_coverage_status']=='passed';tl=tech.read_text();vbody=re.search(r'^\s*VIA\s+Via2_YX\b(.*?)^\s*END Via2_YX',tl,re.M|re.S|re.I)[1];cutbody=re.search(r'LAYER Via2\s*;(.*?)(?=LAYER|$)',vbody,re.S)[1];cuts=len(re.findall(r'RECT ',cutbody));assert cuts>=1;sheet=sum(x['estimated_squares']*layer[n]['sheet_ohm'] for n,x in net['layers'].items());viaR=20/cuts*len(net['via_instances']);wireR=sheet+viaR;cap=sum(s['length_um']*(s['length_um']/s['estimated_squares_from_median_width']*layer[s['layer']]['area_pF_um2']+2*layer[s['layer']]['edge_pF_um']) for s in net['segments'])*1e-12
shutil.copyfile(pex,out/'pex_nominal.spice');provenance={'scope':'Baseline BGR flat/blockCPEX DC load sensitivity; ideal1V IPTAT termination. ExactstockAnalogPad plus0 or sum-of-all-VREF-tree nominalR as a declared conservative series sensitivity, not extractedpoint-to-pointRC. No downstreamSENSE/T2Fdevice loads, package leakage or padstartup qualification.','inputs':{str(x.relative_to(ROOT)) if x.is_relative_to(ROOT) else str(x.relative_to(PDK)):hashlib.sha256(x.read_bytes()).hexdigest() for x in [base,pex,BGR/'.spiceinit',BGR/'manifest.json',geometry,rc,tech,PDK/'libs.ref/sg13g2_io/spice/sg13g2_io.spi']},'wire_only_R_ohm':sheet,'all_tree_via_R_ohm':viaR,'all_tree_R_series_sensitivity_ohm':wireR,'all_tree_C_ground_estimate_F':cap,'Via2_YX_cuts':cuts,'pdk_commit':(PDK/'COMMIT').read_text().strip(),'ngspice_version':subprocess.check_output(['ngspice','--version'],text=True),'image_id':'sha256:5fd78498e578c6e9ec10828c248ca3790fc88250ff6caf545521b29e448ea3c0'};(out/'provenance.json').write_text(json.dumps(provenance,indent=2)+'\n');results=[]
specs=[('baseline',None,None)]+[(f'pad_R{mode}_{load or "open"}',mode,load) for mode in [0,1] for load in [None,1e7,1e6,1e5]]
for name,mode,load in specs:
 leaf=out/name;leaf.mkdir();shutil.copyfile(BGR/'.spiceinit',leaf/'.spiceinit');deck=base.read_text().split('.control')[0].replace('.include pex_nominal.spice','.include ../pex_nominal.spice')
 # Preserve Vdd branch sensing; add independent nominal digital supply for pad.
 if mode is not None:
  deck+=''.join(f'.lib /foss/pdks/ihp-sg13g2/libs.tech/ngspice/models/{lib}.lib {section}\n' for lib,section in [('cornerMOSlv','mos_tt'),('cornerCAP','cap_typ'),('cornerDIO','dio_tt')]);deck+='.include /foss/pdks/ihp-sg13g2/libs.ref/sg13g2_io/spice/sg13g2_io.spi\nVdigital vd 0 1.2\nXP pad padres vd 0 vdd 0 sg13g2_IOPadAnalog\n';deck+=f'Rroute vref route_end {wireR:.16g}\n' if mode else 'Vroute vref route_end 0\n';deck+='Vmeasure route_end padres 0\n'+f'CRa vref 0 {cap/2:.16g}\nCRb padres 0 {cap/2:.16g}\n'
  if load:deck+=f'Rexternal pad 0 {load:.16g}\n'
  vectors='v(vref) v(padres) v(pad) i(vmeasure) i(vload) i(vdd) i(vdigital)'
 else:vectors='v(vref) i(vload) i(vdd)'
 deck+='.control\nset num_threads=1\nset numdgt=15\nset wr_singlescale\nset wr_vecnames\ndc temp -40 125 5\nwrdata '+str(leaf/'wave.tsv')+' '+vectors+'\necho VREF_LOAD_END\nquit 0\n.endc\n.end\n';(leaf/'fixture.cir').write_text(deck)
 with (leaf/'tool.log').open('x') as f:state=run_bounded(['ngspice','-b','fixture.cir'],f,leaf/'run.json',120,cwd=leaf,env=dict(os.environ,OMP_NUM_THREADS='1'),metadata={'deck_sha256':hashlib.sha256((leaf/'fixture.cir').read_bytes()).hexdigest(),'route_mode':mode,'external_R_ohm':load},interval_s=.2)
 wave=leaf/'wave.tsv';rows=[list(map(float,l.split())) for l in wave.read_text().splitlines()[1:]] if wave.exists() else [];log=(leaf/'tool.log').read_text();errors=[x for x in log.splitlines() if re.search(r'(?i)(^Error|fatal|timestep too small|doAnalyses:)',x)];valid=len(rows)==34 and all(len(r)==len(vectors.split())+1 and all(map(math.isfinite,r)) for r in rows);status='passed' if state['returncode']==0 and valid and not errors and 'VREF_LOAD_END' in log else 'failed';record={'name':name,'status':status,'route_mode':mode,'external_R_ohm':load,'wall_s':state['wall_s'],'errors':errors,'columns':['temperature_C']+vectors.split(),'rows':rows,'wave_sha256':hashlib.sha256(wave.read_bytes()).hexdigest() if wave.exists() else None};results.append(record);(out/'manifest.json').write_text(json.dumps({'cases':results,'scope':provenance['scope']},indent=2)+'\n');print(name,status,round(state['wall_s'],3),flush=True)
 if status!='passed':raise SystemExit(1)
