#!/usr/bin/env python3
"""Collect the measurement lines of every run log in logs/ into results/summary.md (Markdown tables).

    python3 summarize.py            (host or container; reads logs/*.log, writes results/summary.md)

The tables are what README.md quotes; the logs are the evidence. A run whose log has no TRIP/POWERUP
line (solver abort) is listed with its last error line.
"""
import glob
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
KV = re.compile(r'([A-Za-z_0-9.]+)=\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)(?=\s|$)')


def parse(path):
    d = {'tag': os.path.basename(path)[:-4], 'wall': None, 'err': None}
    for line in open(path, errors='replace'):
        line = line.rstrip('\n')
        m = re.match(r'^(QUIET|CLOCK|SUPPLY_uA|TRIP|CHARGE|REARM|POWERUP)\b(.*)', line)
        if m:
            for k, v in KV.findall(m.group(2)):
                d[m.group(1) + '.' + k] = v
        if 'Timestep too small' in line:
            d['err'] = re.sub(r'.*doAnalyses', 'doAnalyses', line).strip()[:160]
        m = re.match(r'^# ngspice exit (\d+), wall time (\d+) s', line)
        if m:
            d['wall'] = int(m.group(2))
            d['exit'] = int(m.group(1))
        m = re.match(r'^# (.*)$', line)
        if m and 'desc' not in d and line.startswith('# (') or (m and 'desc' not in d and line.startswith('# quiescent')):
            d['desc'] = m.group(1)
    return d


def f(d, k, fmt='%s', scale=1.0, missing='—'):
    v = d.get(k)
    if v is None or v == '':
        return missing
    try:
        return fmt % (float(v) * scale)
    except ValueError:
        return v


def main():
    logs = sorted(glob.glob(os.path.join(HERE, 'logs', '*.log')))
    runs = [parse(p) for p in logs]
    out = ['# G1_TOP chip-level results (generated by summarize.py from sim/logs/*.log)', '']
    out += ['Simulation completion is separate from functional acceptance. Failed or incomplete runs have no valid final trip verdict; partial quiet-window values are retained below. Missing crossings in completed no-trip cases are not applicable.', '',
            '**Historical runs without `_clockfix` are not accepted timing evidence:** the original ADC clock bridge can double-count edges in Icarus (see `../bridge_probe/README.md`). Their measurements below are retained for diagnosis, not sign-off.', '']
    out.append('## Trip table')
    out.append('')
    out.append('| run | f_osc (MHz) | codes soft/hard | vth_soft / vth_hard (V) | tripped | cause | t(trip_d) us | t(GATE<1 V) us | t(GATE<0.33 V) us | I peak (A) | I end (A) | GATE end (V) | soft_peak | wall (s) | note |')
    out.append('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
    for d in runs:
        if d.get('exit') != 0 or d.get('err'):
            status = 'failed' if d.get('exit') is not None or d.get('err') else 'not run to completion'
            reason = d.get('err') or ('ngspice exit %s' % d['exit'] if 'exit' in d else 'no completion footer; interrupted or still running')
            out.append('| %s | | | | | | | | | | | | | %s | **%s**: %s |' % (d['tag'], d.get('wall') or '—', status, reason))
            continue
        if 'TRIP.tripped_max' not in d and 'POWERUP.GATE_max_EN_low' not in d:
            out.append('| %s | | | | | | | | | | | | | %s | **aborted**: %s |' % (d['tag'], d.get('wall', '—'), d.get('err', 'no measurement lines')))
            continue
        if 'TRIP.tripped_max' not in d:
            continue
        tripped = 'yes' if float(d.get('TRIP.tripped_max', 0) or 0) > 0.6 else 'no'
        cause = {'0': 'none', '1': 'soft', '2': 'hard', '3': 'forced'}.get(f(d, 'TRIP.cause', '%d'), f(d, 'TRIP.cause'))
        out.append('| %s | %s | %s/%s | %s / %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
            d['tag'], f(d, 'CLOCK.f_osc_MHz', '%.2f'), f(d, 'QUIET.code_soft', '%d'), f(d, 'QUIET.code_hard', '%d'),
            f(d, 'QUIET.vth_soft', '%.4f'), f(d, 'QUIET.vth_hard', '%.4f'), tripped, cause,
            f(d, 'TRIP.t_trip_d_us', '%.2f'), f(d, 'TRIP.t_gate_1V_us', '%.2f'), f(d, 'TRIP.t_gate_0.33V_us', '%.2f'),
            f(d, 'TRIP.ipk_A', '%.2f'), f(d, 'TRIP.i_end_A', '%.3f'), f(d, 'TRIP.gate_end', '%.2f'), f(d, 'TRIP.soft_peak', '%d'),
            d.get('wall', '—'), ('completed; functional criteria reviewed separately' if '_clockfix' in d['tag'] else '**failed clock validation; historical diagnostic values only**')))
    out.append('')
    out.append('## Quiet operating values and supply currents (armed, nominal load, before the event)')
    out.append('')
    out.append('| run | VREF (V) | ISENSE (V) | icmp (V) | GATE (V) | I load (A) | VDDA (uA) | IOVDD (uA) | VDD (uA) | bgr | sense | trip 3.3 V | trip 1.2 V | osc | gate 3.3 V | gate 1.2 V |')
    out.append('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
    for d in runs:
        if 'SUPPLY_uA.VDDA' not in d or 'QUIET.vref' not in d or d.get('QUIET.vref') in ('', None):
            continue
        out.append('| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
            d['tag'], f(d, 'QUIET.vref', '%.4f'), f(d, 'QUIET.isense', '%.4f'), f(d, 'QUIET.icmp', '%.4f'), f(d, 'QUIET.gate', '%.2f'),
            f(d, 'QUIET.iload_A', '%.3f'), f(d, 'SUPPLY_uA.VDDA', '%.0f'), f(d, 'SUPPLY_uA.IOVDD', '%.1f'), f(d, 'SUPPLY_uA.VDD', '%.0f'),
            f(d, 'SUPPLY_uA.bgr', '%.1f'), f(d, 'SUPPLY_uA.sense', '%.0f'), f(d, 'SUPPLY_uA.trip_3v3', '%.1f'), f(d, 'SUPPLY_uA.trip_1v2', '%.1f'),
            f(d, 'SUPPLY_uA.osc', '%.0f'), f(d, 'SUPPLY_uA.gate_3v3', '%.2f'), f(d, 'SUPPLY_uA.gate_1v2', '%.2f')))
    out.append('')
    out.append('## Re-arm (case f)')
    out.append('')
    out.append('| run | GATE while EN low (V) | EN high -> GATE 90 % (us) | GATE end (V) | I load end (A) | tripped end (V) |')
    out.append('| --- | --- | --- | --- | --- | --- |')
    for d in runs:
        if 'REARM.gate_while_EN_low' in d:
            out.append('| %s | %s | %s | %s | %s | %s |' % (d['tag'], f(d, 'REARM.gate_while_EN_low', '%.3f'), f(d, 'REARM.EN_high_to_GATE_90pct_us', '%.2f'),
                                                        f(d, 'REARM.gate_end', '%.2f'), f(d, 'REARM.iload_end_A', '%.3f'), f(d, 'REARM.tripped_end', '%.2f')))
    out.append('')
    out.append('## Power-up (case g)')
    out.append('')
    out.append('| run | GATE max while EN low (V) | gate_core max (V) | en_core max (V) | GATE > 1 V from / to (us) | duration (us) | load peak (A) | charge passed (mC) | tripped max (V) | GATE after EN (V) | wall (s) | note |')
    out.append('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
    for d in runs:
        if 'POWERUP.GATE_max_EN_low' in d:
            out.append('| %s | %s | %s | %s | %s / %s | %s | %s | %s | %s | %s | %s | %s |' % (
                d['tag'], f(d, 'POWERUP.GATE_max_EN_low', '%.3f'), f(d, 'POWERUP.gate_core_max', '%.3f'), f(d, 'POWERUP.en_core_max', '%.3f'),
                f(d, 'POWERUP.GATE_above_1V_from_us', '%.2f', 1e6), f(d, 'POWERUP.to_us', '%.2f', 1e6), f(d, 'POWERUP.duration_us', '%.2f'),
                f(d, 'POWERUP.load_peak_A', '%.3f'), f(d, 'POWERUP.charge_As', '%.4f', 1e3), f(d, 'POWERUP.tripped_max', '%.2f'),
                f(d, 'POWERUP.GATE_after_EN', '%.2f'), d.get('wall', '—'), (d.get('err') or '')[:90]))
    with open(os.path.join(HERE, 'results', 'summary.md'), 'w') as fh:
        fh.write('\n'.join(out) + '\n')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
