#!/usr/bin/env python3
"""Convert the frozen xschem netlist ../xschem/g1_bgr.spice into the CDL the PDK LVS deck reads.

Changes are format only: X-prefixed PDK subcircuit calls become M/R/Q elements, `mm_ok` is dropped,
the resistor substrate node `sub!` becomes `vss` (the block's p-substrate is the vss net; in every
simulation deck `sub!` is tied to node 0 together with vss), and the HBT emitter geometry of the PCell
(le=900n we=70n) is written out as the PDK symbol's lvs_format does. The only addition is the layout's
N_DUMMY_HBT dummy npn13G2 devices at the ends of the HBT rows, all four terminals on vss (the layout
ties them to the substrate ring); they carry no current and are not part of the simulated circuit.

  python3 make_lvs_cdl.py            -> writes g1_bgr_lvs.cdl next to this script
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'xschem', 'g1_bgr.spice')
OUT = os.path.join(HERE, 'g1_bgr_lvs.cdl')
N_DUMMY_HBT = 9   # must match layout/g1_bgr_layout.py

out = ['* G1_BGR LVS reference netlist, generated by make_lvs_cdl.py from xschem/g1_bgr.spice (frozen schematic).',
       '* Format conversion only, plus %d dummy HBTs tied to vss (see the docstring of make_lvs_cdl.py).' % N_DUMMY_HBT]
for line in open(SRC):
    line = line.strip()
    if not line or line.startswith('*'):
        continue
    if line.startswith('.subckt') or line.startswith('.ends'):
        out.append(line)
        continue
    f = line.split()
    params = [p for p in f if '=' in p and not p.startswith('mm_ok')]
    if 'sg13_hv_pmos' in f or 'sg13_hv_nmos' in f:
        model = f[5]
        out.append('M%s %s %s %s %s %s %s' % (f[0][1:], f[1], f[2], f[3], f[4], model, ' '.join(params)))
    elif 'rppd' in f or 'rhigh' in f:
        model = f[4]
        sub = 'vss' if f[3] == 'sub!' else f[3]
        out.append('R%s %s %s %s %s %s' % (f[0][1:], f[1], f[2], sub, model, ' '.join(params)))
    elif 'npn13G2' in f:
        nx = [p for p in params if p.startswith('Nx=')][0]
        out.append('Q%s %s %s %s %s npn13G2 le=900n we=70n %s' % (f[0][1:], f[1], f[2], f[3], f[4], nx))
    else:
        raise SystemExit('unhandled line: ' + line)
ends = out.pop()
assert ends.startswith('.ends')
for k in range(N_DUMMY_HBT):
    out.append('QDUM%d vss vss vss vss npn13G2 le=900n we=70n Nx=1' % (k + 1))
out.append(ends)
with open(OUT, 'w') as fh:
    fh.write('\n'.join(out) + '\n')
print('wrote', OUT, len(out), 'lines')
