#!/usr/bin/env python3
"""Convert an xschem/ngspice netlist of a G1 analog block into a CDL for the PDK KLayout LVS deck.

The xschem netlists instantiate the PDK primitives as subcircuits (X-lines: sg13_hv_pmos, sg13_lv_nmos,
rppd, cap_cmim). The LVS reader (libs.tech/klayout/tech/lvs/rule_decks/custom_reader.lvs) recognises
only M/R/C/Q/L/D elements, so this script rewrites:

  XM1 d g s b sg13_hv_pmos w=96u l=2u ng=16 m=1 mm_ok=1   ->  MM1 d g s b sg13_hv_pmos w=96u l=2u m=1
  XR1 a b sub! rppd w=2u l=76.7u m=1 b=0 mm_ok=1          ->  RR1 a b vss rppd w=2u l=76.7u m=1 b=0
  XC1 p n cap_cmim w=23u l=23u m=1 mm_ok=1                ->  CC1 p n cap_cmim w=23u l=23u m=1

Conventions (documented in the block READMEs):
  * `sub!` (the resistor body's substrate terminal) is the block's substrate = the ground net given
    with --sub (default vss); the layout ties the substrate to that net with p+ guard rings.
  * `ng` (finger count) is dropped: the reader takes `w` as the total width and the extracted netlist
    combines the parallel fingers of one device (LVS "simplify"), so only the total W and L are compared.
  * `mm_ok` (xschem mismatch flag) is dropped. Hierarchy (.subckt of locally generated cells) is kept.
Usage: python3 spice2cdl.py in.spice out.cdl [--sub vss]
"""
import re, sys

PRIM = {'sg13_hv_pmos': 'M', 'sg13_hv_nmos': 'M', 'sg13_lv_pmos': 'M', 'sg13_lv_nmos': 'M',
        'rppd': 'R', 'rhigh': 'R', 'rsil': 'R', 'cap_cmim': 'C'}
DROP = {'ng', 'mm_ok'}

def convert(lines, sub='vss'):
    out = []
    for raw in lines:
        line = raw.rstrip('\n')
        if not line or line.startswith('*') or line.startswith('**'):
            if line.startswith('.subckt') or line.startswith('.ends'):
                out.append(line)
            continue
        if line.startswith('+ '):
            out[-1] += ' ' + line[2:]
            continue
        toks = line.split()
        if toks[0][0] in 'Xx':
            # find the model token: first token that is a known primitive or has no '='
            params = [t for t in toks[1:] if '=' in t]
            nets_model = [t for t in toks[1:] if '=' not in t]
            model = nets_model[-1]
            nets = nets_model[:-1]
            if model in PRIM:
                nets = [sub if n == 'sub!' else n for n in nets]
                params = [p for p in params if p.split('=')[0] not in DROP]
                out.append(' '.join([PRIM[model] + toks[0][1:]] + nets + [model] + params))
                continue
        out.append(line)
    return out

if __name__ == '__main__':
    args = sys.argv[1:]
    sub = 'vss'
    if '--sub' in args:
        i = args.index('--sub'); sub = args[i + 1]; del args[i:i + 2]
    src, dst = args
    res = convert(open(src).read().splitlines(), sub)
    with open(dst, 'w') as f:
        f.write('* CDL for KLayout LVS, generated by layout/spice2cdl.py from %s (substrate net = %s)\n' % (src.split('/')[-1], sub))
        f.write('\n'.join(res) + '\n')
    print('wrote', dst, len(res), 'lines')
