#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Convert the LibreLane powered gate-level Verilog netlist (final/pnl/*.pnl.v)
of g1_chip_top into a CDL netlist for the PDK KLayout LVS deck.

  python3 pnl2cdl.py <design.pnl.v> <out.cdl> <cdl-library> [<cdl-library> ...]

The output is the concatenation of the given CDL libraries (pin order of every
cell is taken from their .SUBCKT lines), an empty subcircuit for the bondpad
cell (metal only, no devices) and the top-level subcircuit. Unconnected
instance pins get unique `_nc<n>` nets. Escaped Verilog identifiers are
un-escaped; '.', '[' and ']' in net names are replaced by '_'.

`padbare` of sg13g2_IOPadAnalog (ip/sg13g2_io_padbare) is the same conductor
as `pad`; the CDL cell has no such pin. The net on `padbare` is therefore
merged into the net on `pad` throughout the top level, which is exactly what
the Verilog model (`assign pad = padbare`) and the layout say.
"""
import re
import sys

pnl, out, *libs = sys.argv[1:]
text = open(pnl).read()

pin_order = {}
lib_text = []
for lib in libs:
    t = open(lib).read()
    lib_text.append(t)
    lines = t.splitlines()
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.upper().startswith(".SUBCKT"):
            toks = ln.split()
            while i + 1 < len(lines) and lines[i + 1].startswith("+"):
                i += 1
                toks += lines[i].split()[1:]
            pin_order[toks[1]] = toks[2:]
        i += 1

def san(n):
    n = n.strip()
    if n.startswith("\\"):
        n = n[1:].strip()
    return re.sub(r"[.\[\]]", "_", n)

m = re.search(r"module\s+(\w+)\s*\((.*?)\);", text, re.S)
top = m.group(1)
ports = [san(p) for p in m.group(2).replace("\n", " ").split(",") if p.strip()]
body = text[m.end():]
body = re.sub(r"//.*", "", body)

inst_re = re.compile(r"^\s*(\w+)\s+(\\\S+\s|\S+)\s*\((.*?)\);", re.S | re.M)
# a connection is .pin(net) or .bus({netN, ..., net0}) (concatenation, MSB first)
conn_re = re.compile(r"\.(\w+)\s*\(\s*(\{[^}]*\}|[^(){}]*)\)")
SAME_CONDUCTOR = {"sg13g2_IOPadAnalog": ("padbare", "pad")}
alias = {}
insts = []
for mm in inst_re.finditer(body):
    cell, inst, conns = mm.group(1), san(mm.group(2)), mm.group(3)
    if cell in ("wire", "input", "output", "inout", "assign", "module"):
        continue
    conn = {}
    for k, v in conn_re.findall(conns):
        v = v.strip()
        if v.startswith("{"):
            bits = [b for b in v.strip("{}").replace("\n", " ").split(",") if b.strip()]
            n = len(bits)
            for idx, b in enumerate(bits):          # MSB first
                conn[f"{k}[{n - 1 - idx}]"] = san(b)
        else:
            conn[k] = san(v) if v else ""
    if cell in SAME_CONDUCTOR:
        a, b = SAME_CONDUCTOR[cell]
        if conn.get(a) and conn.get(b) and conn[a] != conn[b]:
            alias[conn[a]] = conn[b]
            print(f"merge net {conn[a]} into {conn[b]} ({inst}.{a} = {inst}.{b})")
    insts.append((cell, inst, conn))

def res(n):
    while n in alias:
        n = alias[n]
    return n

nc = 0
lines_out = [f".SUBCKT {top} " + " ".join(res(p) for p in ports)]
counts = {}
for cell, inst, conn in insts:
    if cell == "bondpad_70x70_tm1":
        order = ["pad"]
    elif cell in pin_order:
        order = pin_order[cell]
    else:
        sys.exit(f"no CDL subcircuit for cell {cell}")
    nets = []
    for p in order:
        v = conn.get(p, "")
        if v == "":
            nc += 1
            v = f"_nc{nc}"
        nets.append(res(v))
    lines_out.append(f"X{inst} " + " ".join(nets) + f" / {cell}")
    counts[cell] = counts.get(cell, 0) + 1
lines_out.append(".ENDS")

with open(out, "w") as f:
    f.write("* schematic netlist for KLayout LVS, generated by pnl2cdl.py from " + pnl + "\n")
    for t in lib_text:
        f.write(t + "\n")
    f.write(".SUBCKT bondpad_70x70_tm1 pad\n*.PININFO pad:B\n* metal-only bond pad, no devices\n.ENDS\n\n")
    f.write("\n".join(lines_out) + "\n")
print(f"{top}: {sum(counts.values())} instances, {nc} unconnected pins")
for c in sorted(counts):
    print(f"  {counts[c]:6d} {c}")
