#!/usr/bin/env python3
"""Derive a pin-compatible re-hardening config from ../config_tmr_spread.yaml (run7).

Changes against run7, nothing else:
  * VERILOG_FILES read from --rtl (the g1_seu RTL stays ../../g1_seu/rtl);
  * FP_DEF_TEMPLATE = g1_digital_pins_run7.def (44 signal pins of run7, which are
    the pins of the chip's macro), strict match: pins copied, not re-placed;
  * RT_MAX_LAYER Metal5 (no TopMetal signal wires under the chip's TM1 stripes/fill);
  * CTS_SINK_CLUSTERING_SIZE 8 and step G1.SplitClockRoot after OpenROAD.CTS
    (librelane_plugin_g1eco) (as in the chip macro's redone CTS,
    review/audits/DIGITAL_CTS_FANOUT_20260923.md);
  * MANUAL_GLOBAL_PLACEMENTS: --seeds run7 keeps run7's seeds (valid only for the
    run7 RTL), --seeds none drops them (pass 1 of an RTL change), --seeds <yaml>
    takes the output of ../tmr_spread.py (pass 2).
Usage: make_config.py --rtl <dir relative to flow/eco> [--seu-rtl <dir>] --seeds run7|none|<yaml> --out <config.yaml>
"""
import argparse
import os
import re

p = argparse.ArgumentParser()
p.add_argument('--rtl', required=True)
p.add_argument('--seeds', required=True)
p.add_argument('--seu-rtl', default='../../../g1_seu/rtl')
p.add_argument('--out', required=True)
a = p.parse_args()

base = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'config_tmr_spread.yaml')).read()
cut = base.index('# --- TMR copy separation seeds')
head, seeds = base[:cut], base[cut:]
head = head.replace('dir::../rtl/', 'dir::%s/' % a.rtl.rstrip('/'))
head = head.replace('dir::../../g1_seu/rtl/', 'dir::%s/' % a.seu_rtl.rstrip('/'))
head = head.replace('dir::g1_digital.sdc', 'dir::../g1_digital.sdc')
assert head.count('dir::%s/' % a.seu_rtl.rstrip('/')) == 3
assert head.count('dir::%s/' % a.rtl.rstrip('/')) == 6 and head.count('dir::../g1_digital.sdc') == 3
head = ('# GENERATED by eco/make_config.py --rtl %s --seu-rtl %s --seeds %s; do not edit.\n' % (a.rtl, a.seu_rtl, a.seeds)) + head
sub = '    "-OpenROAD.RepairDesignPostGPL": Odb.ManualGlobalPlacement\n'
assert head.count(sub) == 1
head = head.replace(sub, sub + '    # clock-root fanout split after CTS (eco/librelane_plugin_g1eco)\n'
                    '    "+OpenROAD.CTS": G1.SplitClockRoot\n')
head += '''
# --- pin compatibility with the chip macro (eco/make_config.py) ---
FP_DEF_TEMPLATE: dir::g1_digital_pins_run7.def
FP_TEMPLATE_MATCH_MODE: strict
# clock-tree fanout <= 8 (liberty default_max_fanout), as the chip macro's redone CTS
CTS_SINK_CLUSTERING_SIZE: 8
# no signal routing on TopMetal1/TopMetal2: the chip's own TopMetal1 stripes cross
# the macro (macro x = 64.4-70.4, 140-146, 215.6-221.6, 291.2-297.2 um) and the chip's
# TopMetal1/2 fill sits between the macro's TopMetal shapes; with Metal5 as the top
# routing layer the macro's TopMetal content is its PDN only, a subset of the chip macro's
RT_MAX_LAYER: Metal5

'''
if a.seeds == 'run7':
    body = seeds
elif a.seeds == 'none':
    body = ''
else:
    body = '# --- TMR copy separation seeds from %s ---\n' % a.seeds + open(a.seeds).read()
open(a.out, 'w').write(head + body)
print('wrote', a.out)
