#!/usr/bin/env python3
"""Write a pin-only DEF template (FP_DEF_TEMPLATE) from a g1_digital DEF.

Keeps the DEF header, DIEAREA and the signal pins of the PINS section; drops
rows, tracks, components, nets and the VDD/VSS special pins (those are made by
the PDN step from the unchanged PDN configuration).
Usage: make_pin_template.py <source.def> <template.def>
"""
import hashlib
import re
import sys

src, dst = sys.argv[1:3]
text = open(src).read()
head = text[:text.index('DIEAREA')]
diearea = re.search(r'^DIEAREA .*;$', text, re.M).group(0)
pins = text[text.index('\nPINS ') + 1:text.index('END PINS')]
blocks = re.split(r'\n(?=    - )', pins)[1:]           # one block per pin
signal = [b.rstrip('\n') for b in blocks if '+ SPECIAL' not in b]
out = (head.replace('VERSION 5.8 ;', '# generated by make_pin_template.py from\n# %s sha256 %s\nVERSION 5.8 ;'
                    % (src.split('/work/')[-1], hashlib.sha256(text.encode()).hexdigest()), 1)
       + diearea + '\nPINS %d ;\n' % len(signal) + '\n'.join(signal) + '\nEND PINS\nEND DESIGN\n')
open(dst, 'w').write(out)
print('%d signal pins written to %s' % (len(signal), dst))
