#!/usr/bin/env python3
"""Summarize retained HBT self-heating sensitivities and model-range limits."""
import argparse,hashlib,json
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--screen',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(exist_ok=False);(a.output/'runner.py').write_text(Path(__file__).read_text());cases=json.loads((a.screen/'manifest.json').read_text())['cases'];assert len(cases)==24 and all(x['status']=='passed' for x in cases);comparisons=[]
for on in [x for x in cases if x['selft']==1]:
 off=next(x for x in cases if x['corner']==on['corner'] and x['ambient_C']==on['ambient_C'] and x['selft']==0);rows=[]
 for anchor in on['anchors']:
  other=next((x for x in off['anchors'] if x['target_IC_A']==anchor['target_IC_A']),None)
  if other:rows.append({'IC_A':anchor['target_IC_A'],'VBE_on_V':anchor['VBE_V'],'VBE_off_V':other['VBE_V'],'VBE_on_minus_off_V':anchor['VBE_V']-other['VBE_V'],'selfheat_rise_K':anchor['temperature_rise_K'],'junction_C':anchor['junction_C'],'VCE_on_V':anchor['VCE_V'],'IB_on_A':anchor['IB_A'],'collector_pad_A':anchor['collector_pad_A'],'inside_bias_and_junction_range':.65<=anchor['VBE_V']<=.96 and .4<=anchor['VCE_V']<=1.6 and anchor['target_IC_A']<.003 and -40<=anchor['junction_C']<=125})
 comparisons.append({'corner':on['corner'],'ambient_C':on['ambient_C'],'max_rise_K':on['maximum_temperature_rise_K'],'max_IC_on_A':on['maximum_IC_A'],'max_IC_off_A':off['maximum_IC_A'],'max_base_point_IC_relative_change':on['maximum_IC_A']/off['maximum_IC_A']-1,'junction_above_125C_points':on['junction_above_125C_count'],'bias_outside_stated_range_points':on['outside_stated_bias_count'],'anchors':rows})
result={'scope':'Model-based DC self-heating sensitivity with detailed pads and estimated routeRC. No package/chip thermal coupling or measured thermal calibration.','inputs':{str(a.screen/f):hashlib.sha256((a.screen/f).read_bytes()).hexdigest() for f in ['manifest.json','provenance.json']},'numerical_status':'passed','paired_corner_temperature_conditions':12,'sweeps':24,'total_DC_points':24*551,'VCE_1p6_limit_status':'passed' if all(x['VCE_over_1p6_count']==0 for x in cases) else 'failed','all_selft0_temperature_zero':all(x['maximum_temperature_rise_K']==0 for x in cases if x['selft']==0),'comparisons':comparisons,'largest_selfheat_rise_K':max(x['max_rise_K'] for x in comparisons),'full_bias_temperature_qualification':'not run: off-region Gummel points and all125C selfheated sweeps exceed at least one stated model-range condition','package_selfheating_and_pulsed_readout':'not run'};(a.output/'summary.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
