#!/usr/bin/env python3
"""Run only the stock sg13g2_maximal deck through the PDK's own run_drc.py API.
Switches are generated by run_drc.generate_klayout_switches for the same arguments as
`run_drc.py --run_mode=deep --no_density --density_thr=N`, i.e. what run_drc.py itself
passes to sg13g2_maximal.drc; the stock run_drc.py CLI has no maximal-only option.
Same method as review/audits/run_core_candidate_drc.py --execute maximal.
Usage: python3 run_maximal.py <gds> <topcell> <run_dir> <threads>"""
import importlib.util, sys
from pathlib import Path
from types import SimpleNamespace
DRC = Path('/foss/pdks/ihp-sg13g2/libs.tech/klayout/tech/drc')
gds, top, run_dir, thr = sys.argv[1], sys.argv[2], Path(sys.argv[3]), int(sys.argv[4])
sys.path.insert(0, str(DRC))
spec = importlib.util.spec_from_file_location('pinned_stock_drc', DRC / 'run_drc.py')
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
args = SimpleNamespace(density_thr=thr, drc_json=None, run_mode='deep', precheck_drc=False,
                       disable_extra_rules=False, no_feol=False, no_beol=False, no_offgrid=False,
                       no_angle=False, density_sanity=False, no_density=True, no_recommended=False,
                       table=[], topcell=top)
sw = m.generate_klayout_switches(args, str(Path(gds).resolve()))
run_dir.mkdir(parents=True, exist_ok=True)
print({k: str(v) for k, v in sw.items()}, flush=True)
print(m.run_check(DRC / 'rule_decks/sg13g2_maximal.drc', ['sg13g2_maximal'], str(Path(gds).resolve()), run_dir, sw))
