#!/usr/bin/env python3
"""Write the LVS reference netlist g1_t2f_lvs.cdl from the frozen xschem netlist ../xschem/g1_t2f.spice.

The KLayout LVS deck (PDK commit 8437402, rule_decks/custom_reader.lvs) reads devices as M/Q/R/C
elements, not as X subcircuit calls, so every xschem line is rewritten:
  XMPO d g s b sg13_hv_pmos w= l= ng= m= mm_ok=1 -> MMPO d g s b sg13_hv_pmos w= l= ng= m=   (mm_ok dropped)
  XQA1 c b e s npn13G2 Nx=1 mm_ok=1                -> QQA1 c b e s npn13G2 le=900n we=70n Nx=1  (PCell default emitter)
  XRREF1 p m sub! rppd w= l= m= b= mm_ok=1         -> RRREF1 p m vss rppd w= l= b= m=             (substrate = vss in the layout;
                                                        ten 24.5 um units as in the layout, compared one-to-one with --no_series_res)
  XC1 a b cap_cmim w= l= m= mm_ok=1                -> CC1 a b cap_cmim w= l= m=                    (a = TopMetal1 plate)
and the two dummy HBTs of the comparator row (all terminals on the vss ring) are appended. These are the
only differences between the simulated netlist and the LVS reference; the README lists them.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'xschem', 'g1_t2f.spice')
OUT = os.path.join(HERE, 'g1_t2f_lvs.cdl')

out = ['* G1_T2F LVS reference, generated by make_lvs_cdl.py from xschem/g1_t2f.spice (frozen schematic)']
for line in open(SRC):
    line = line.strip()
    if not line or line.startswith('*'):
        continue
    if line.startswith('.subckt') or line.startswith('.ends'):
        out.append(line)
        continue
    if not line.startswith('X'):
        raise SystemExit('unexpected line: ' + line)
    tok = line.split()
    params = [t for t in tok if '=' in t and not t.startswith('mm_ok')]
    body = [t for t in tok if '=' not in t]
    name, nets, model = body[0][1:], body[1:-1], body[-1]
    nets = ['vss' if n == 'sub!' else n for n in nets]
    if model in ('sg13_hv_pmos', 'sg13_hv_nmos', 'sg13_lv_pmos', 'sg13_lv_nmos'):
        out.append(' '.join(['M' + name] + nets + [model] + params))
    elif model == 'npn13G2':
        nx = [p for p in params if p.startswith('Nx=')] or ['Nx=1']
        out.append(' '.join(['Q' + name] + nets + [model, 'le=900n', 'we=70n'] + nx))
    elif model == 'rppd':
        out.append(' '.join(['R' + name] + nets + [model] + params))
    elif model == 'cap_cmim':
        out.append(' '.join(['C' + name] + nets + [model] + params))
    else:
        raise SystemExit('unknown model: ' + line)
ends = out.pop()
out += ['QQD1 vss vss vss vss npn13G2 le=900n we=70n Nx=1', 'QQD2 vss vss vss vss npn13G2 le=900n we=70n Nx=1', ends]
open(OUT, 'w').write('\n'.join(out) + '\n')
print('wrote', OUT, len(out), 'lines')
