#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate an UNPROMOTED local-cell/source patch from the checked P01 candidate.

Input geometry is generated by review/audits/geometry_candidates.py, mode
pad_outward_dummy_clean. This tool never writes production views or installed
PDK files. The resulting patch and copied timing tables require review and
fresh full-flow/electrical qualification before adoption.
"""
import argparse
import csv
import difflib
import hashlib
import json
from pathlib import Path
import re
import pya

ROOT=Path(__file__).resolve().parents[6]
BLOCK=ROOT/'designs/g1-guardian/blocks/g1_padring'
IO='sg13g2_IOPadIn_g1_vdddummy'
BOND='bondpad_70x70_tm1_g1_exit'

def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()

def bounded_block(text,start):
    """A Liberty cell block including nested groups."""
    begin=text.index(start);opening=text.index('{',begin);depth=1;i=opening+1
    while depth:
        depth+=(text[i]=='{')-(text[i]=='}');i+=1
    return text[begin:i]

p=argparse.ArgumentParser(description=__doc__)
p.add_argument('--candidate',type=Path,required=True)
p.add_argument('--manifest',type=Path,required=True)
p.add_argument('--output',type=Path,required=True)
a=p.parse_args()
if a.output.exists():raise FileExistsError('Do not overwrite prior proposal')
manifest=json.loads(a.manifest.read_text())
assert manifest['mode']=='pad_outward_dummy_clean'
assert sha(a.candidate)==manifest['candidate_sha256']
assert all(c['status']=='passed' for c in manifest['checks']) and len(manifest['checks'])==3
out=a.output;out.mkdir(parents=True)
views=out/'ip/g1_p01';views.mkdir(parents=True)
layout=pya.Layout();layout.read(str(a.candidate));top=layout.cell('g1_chip_top')
io=layout.cell('sg13g2_IOPadIn');io.name=IO
bond=layout.cell('bondpad_70x70_tm1');bond.name=BOND
# The shifted pad needs a 4-um metal extension toward its IO stub. The checked
# candidate already has this geometry in top-level rectangles. Put it into
# the local bondpad source too; existing overlapping top metal is retained.
for layer in (126,134):
    bond.shapes(layout.layer(layer,0)).insert(pya.DBox(0,70,70,74).to_itype(layout.dbu))
bond.write(str(views/(BOND+'.gds')))
layout.write(str(out/'g1_chip_top_proposed.gds'))
# Verify that moving the checked extension into the cell adds no new geometry.
original=pya.Layout();original.read(str(a.candidate));changed=[]
for li in original.layer_indexes():
    info=original.get_info(li)
    lhs=pya.Region(original.cell('g1_chip_top').begin_shapes_rec(li)).merged()
    rhs=pya.Region(top.begin_shapes_rec(layout.layer(info))).merged()
    delta=lhs^rhs
    if not delta.is_empty():changed.append({'layer':str(info),'area_um2':delta.area()*layout.dbu**2})
assert not changed,changed
# Future assemblies must regenerate fill around the added device. No-fill
# metadata is added to the standalone local source cell, after writing the
# geometrically identical proposed full-chip snapshot above.
for layer in (1,5,8):
    io.shapes(layout.layer(layer,23)).insert(pya.DBox(33.5,158.95,40,169.77).to_itype(layout.dbu))
io.write(str(views/(IO+'.gds')))
# Independent explicit schematic intent. Original device/net statements stay.
cdl=(BLOCK/'netlist/g1_chip_top.cdl').read_text()
start=cdl.index('.SUBCKT sg13g2_IOPadIn ');end=cdl.index('.ENDS',start)
added='MP_G1_VDD_ANT vdd vdd vdd vdd sg13_hv_pmos m=1 w=4.65u l=450n ng=1\n'
cdl=cdl[:end]+added+cdl[end:]
cdl=re.sub(r'\bsg13g2_IOPadIn\b',IO,cdl)
cdl=re.sub(r'\bbondpad_70x70_tm1\b',BOND,cdl)
(out/'g1_chip_top_proposed.cdl').write_text(cdl)
local_io=re.search(r'\.SUBCKT '+IO+r'\b.*?\.ENDS[^\n]*',cdl,re.S).group()
(views/'g1_p01.cdl').write_text('* SPDX-License-Identifier: Apache-2.0\n* Derived from IHP PDK Authors sg13g2_IOPadIn, Copyright 2023.\n* Requires stock sg13g2_io.cdl for unchanged child definitions.\n'+local_io+'\n\n.SUBCKT '+BOND+' pad\n* metal-only bondpad\n.ENDS\n')
# IO LEF ports/outline/obstructions unchanged; append cloned macro.
iolef=(BLOCK/'ip/sg13g2_io_padbare/lef/sg13g2_io.lef').read_text()
macro=re.search(r'MACRO sg13g2_IOPadIn\b.*?END sg13g2_IOPadIn\b',iolef,re.S).group()
clone=re.sub(r'\bsg13g2_IOPadIn\b',IO,macro)
iolef=iolef.replace('END LIBRARY',clone+'\nEND LIBRARY') if 'END LIBRARY' in iolef else iolef+'\n'+clone+'\n'
(views/'sg13g2_io_with_g1.lef').write_text(iolef)
bondlef=(BLOCK/'ip/bondpad_70x70_tm1/lef/bondpad_70x70_tm1.lef').read_text().replace('bondpad_70x70_tm1',BOND).replace('SIZE 70.0 BY 70.0','SIZE 70.0 BY 74.0').replace('RECT 0 0 70.0 70.0','RECT 0 0 70.0 74.0')
(views/(BOND+'.lef')).write_text(bondlef)
# Functional model and inherited timing are copies for a flow rehearsal only.
verilog=(BLOCK/'ip/sg13g2_io_padbare/verilog/sg13g2_io.v').read_text()
module=re.search(r'module sg13g2_IOPadIn\b.*?endmodule',verilog,re.S).group()
(views/'sg13g2_io_with_g1.v').write_text(verilog+'\n// UNQUALIFIED derived-cell functional model; all-VDD added device omitted digitally.\n'+re.sub(r'\bsg13g2_IOPadIn\b',IO,module)+'\n')
for source in sorted((BLOCK/'ip/sg13g2_io_padbare/lib').glob('*.lib')):
    txt=source.read_text();block=bounded_block(txt,'cell (sg13g2_IOPadIn)')
    clone=block.replace('cell (sg13g2_IOPadIn)','cell ('+IO+')',1)
    pos=txt.rfind('}');txt=txt[:pos]+'\n/* UNQUALIFIED copied stock timing for flow rehearsal only. */\n'+clone+'\n'+txt[pos:]
    (views/source.name).write_text(txt)
# Pad-map delta is keyed by original DEF component and corresponding pad net.
defpath=BLOCK/'flow/runs/assembly-1350/final/def/g1_chip_top.def';deftxt=defpath.read_text()
components=deftxt[deftxt.index('COMPONENTS'):deftxt.index('END COMPONENTS')]
records=[]
for m in re.finditer(r'-\s+(IO_BOND_\S+)\s+bondpad_70x70_tm1\s+\+\s+FIXED\s*\(\s*(-?\d+)\s+(-?\d+)\s*\)\s*(\w+)',components):
    name,x,y,orientation=m.groups();records.append((name,int(x)/1000+35,int(y)/1000+35,orientation))
assert len(records)==24
with (out/'padmap_delta.csv').open('w') as f:
    writer=csv.writer(f);writer.writerow(['bondpad_instance','orientation','old_center_x_um','old_center_y_um','new_center_x_um','new_center_y_um','delta_x_um','delta_y_um'])
    for name,x,y,orientation in sorted(records):
        row=next(r for r in manifest['moved_bondpads'] if abs(r['original_center_um'][0]-x)<.001 and abs(r['original_center_um'][1]-y)<.001)
        writer.writerow([name,orientation,x,y,*row['new_center_um'],*row['shift_um']])
# Reviewable patch only; no production source file is edited.
patch=[]
for cfg in ('config.yaml','config_dryrun.yaml'):
    path=BLOCK/'flow'/cfg;old=path.read_text();new=old.replace('PAD_BONDPAD_NAME: bondpad_70x70_tm1','PAD_BONDPAD_NAME: '+BOND+'\nPAD_BONDPAD_OFFSETS: [5.0, -74.0]')
    new=new.replace('dir::../ip/bondpad_70x70_tm1/gds/bondpad_70x70_tm1.gds','dir::../ip/g1_p01/'+BOND+'.gds\n  - dir::../ip/g1_p01/'+IO+'.gds')
    new=new.replace('dir::../ip/bondpad_70x70_tm1/lef/bondpad_70x70_tm1.lef','dir::../ip/g1_p01/'+BOND+'.lef')
    new=new.replace('  - bondpad_70x70_tm1\n','  - '+BOND+'\n')
    new=new.replace('ip/sg13g2_io_padbare/lef/sg13g2_io.lef','ip/g1_p01/sg13g2_io_with_g1.lef').replace('ip/sg13g2_io_padbare/verilog/sg13g2_io.v','ip/g1_p01/sg13g2_io_with_g1.v').replace('ip/sg13g2_io_padbare/lib/','ip/g1_p01/')
    relative=str(path.relative_to(ROOT));patch.extend(difflib.unified_diff(old.splitlines(True),new.splitlines(True),fromfile='a/'+relative,tofile='b/'+relative))
path=BLOCK/'rtl/g1_chip_top.sv';old=path.read_text();new=re.sub(r'\bsg13g2_IOPadIn\b',IO,old)
relative=str(path.relative_to(ROOT));patch.extend(difflib.unified_diff(old.splitlines(True),new.splitlines(True),fromfile='a/'+relative,tofile='b/'+relative))
(out/'proposed_adoption.patch').write_text(''.join(patch))
(out/'fill_keepout.json').write_text(json.dumps({'scope':'Inserted in standalone derived IO source; not inserted in the identical full-chip snapshot','cell':IO,'local_bbox_um':[33.5,158.95,40,169.77],'no_fill_layers':[[1,23],[5,23],[8,23]],'regenerated_fill_status':'not run'},indent=2)+'\n')
result={'script_sha256':sha(Path(__file__)),'source_only_metadata':'Datatype-23 no-fill boxes on Activ/GatPoly/Metal1 in standalone derived IO GDS; fresh refill/checks required','status':'proposal only; NOT PROMOTED','input_candidate_sha256':sha(a.candidate),'all_layer_polygon_identity':'passed','changed_polygon_layers':changed,
        'text_comparison':'not run','derived_io_cell':IO,'derived_bondpad_cell':BOND,'explicit_added_device':added.strip(),
        'stock_timing_recharacterization':'not run; copied tables are unqualified','fresh_flow_and_fill':'not run',
        'files':{str(f.relative_to(out)):sha(f) for f in sorted(out.rglob('*')) if f.is_file()}}
(out/'manifest.json').write_text(json.dumps(result,indent=2)+'\n')
print(json.dumps({'status':result['status'],'all_layer_polygon_identity':'passed','generated_files':len(result['files'])},indent=2))
