#!/usr/bin/env python3
"""Scoped block-current and rail-energy audit of a completed integrated waveform."""
import argparse,hashlib,json,shutil
from pathlib import Path
import numpy as np
p=argparse.ArgumentParser(description=__doc__);p.add_argument('--run',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();a.output.mkdir(exist_ok=False);shutil.copyfile(__file__,a.output/'analyzer.py');wave=a.run/'observations.tsv';acc=json.loads((a.run/'electrical_acceptance.json').read_text());assert acc['status']=='passed';assert hashlib.sha256(wave.read_bytes()).hexdigest()==acc['waveform_sha256'];cols=wave.open().readline().split();d=np.loadtxt(wave,skiprows=1);assert np.isfinite(d).all() and np.all(np.diff(d[:,0])>0) and d[-1,0]>=28e-6;lookup={s:i for i,s in enumerate(cols)};records=[]
blocks={'BGR':('v(vdda)','i(vm_bgr)'),'SENSE':('v(vdda)','i(vm_sense)'),'TRIP_analog':('v(vdda)','i(vm_tripa)'),'TRIP_digital':('v(vdd)','i(vm_tripd)'),'GATE_analog':('v(vdda)','i(vm_gatea)'),'GATE_digital':('v(vdd)','i(vm_gated)'),'OSC_dummy_only':('v(vdd)','i(vm_osc)')};windows={'idle_ENlow':(1e-6,2.8e-6),'configuration_active':(4e-6,10e-6),'armed_before_fault':(14e-6,15.9e-6),'tripped':(20e-6,28e-6)}
for name,(start,end) in windows.items():
 time=np.r_[start,d[(d[:,0]>start)&(d[:,0]<end),0],end];v={s:np.interp(time,d[:,0],d[:,i]) for s,i in lookup.items()};integ=lambda x:float(np.trapz(x,time));mean=lambda x:integ(x)/(end-start);rec={'window':name,'start_s':start,'end_s':end,'rows_with_interpolated_boundaries':len(time),'states':{s:{'min':float(v[s].min()),'max':float(v[s].max())} for s in ['v(en_core)','v(gate)','v(tripped)','v(soft_armed)','v(dig_trip)','v(cause1)','v(cause0)','v(vdda)','v(vdd)','v(iovdd)']},'blocks':{}}
 for b,(rail,current) in blocks.items():
  i=v[current];power=v[rail]*i;rec['blocks'][b]={'mean_current_A':mean(i),'sampled_min_current_A':float(i.min()),'sampled_max_current_A':float(i.max()),'mean_rail_supplied_power_W':mean(power),'rail_supplied_energy_J':integ(power)}
 rec['named_analog_rail_power_W']=sum(x['mean_rail_supplied_power_W'] for b,x in rec['blocks'].items() if blocks[b][0]=='v(vdda)');rec['named_digital_rail_power_W']=sum(x['mean_rail_supplied_power_W'] for b,x in rec['blocks'].items() if blocks[b][0]=='v(vdd)')
 rec['rails']={}
 for rail,source,sgn,names in [('v(vdda)','i(vma)',1,['BGR','SENSE','TRIP_analog','GATE_analog']),('v(vdd)','i(v12)',-1,['TRIP_digital','GATE_digital','OSC_dummy_only']),('v(iovdd)','i(vmi)',1,[])]:
  supplied=v[source]*sgn;known=sum((v[blocks[b][1]] for b in names),np.zeros_like(time));qd=1e-9*(v[rail][-1]-v[rail][0]);res=integ(supplied-known)-qd;rec['rails'][rail]={'mean_upstream_source_current_A':mean(supplied),'source_charge_C':integ(supplied),'named_block_charge_C':integ(known),'local_1nF_cap_delta_charge_C':float(qd),'unassigned_charge_after_cap_C':res,'unassigned_equivalent_mean_current_A':res/(end-start),'interpretation':'VDDA probes cover all stated branches; residual is sampled charge balance diagnostic, no assigned numerical tolerance.' if rail=='v(vdda)' else 'Unprobed pad/behavioral branches may remain; residual is not a pure KCL numerical error.','local_voltage_min_V':float(v[rail].min()),'local_voltage_max_V':float(v[rail].max())}
 records.append(rec)
summary={'scope':'Simulated nominal completed compact CPEX analog/RTL functional fixture, not whole-chip power or assembledIR. Positive0Vprobe current enters block. Rail-supplied power is not thermal dissipation when output/input sources exchange energy.','checks':{'completed_electrical_acceptance':True,'wave_hash_matches_acceptance':True,'finite_strictly_increasing_data':True},'inputs':{f.name:hashlib.sha256(f.read_bytes()).hexdigest() for f in [wave,a.run/'fixture.cir',a.run/'electrical_acceptance.json',a.run/'assessment.json',a.run/'run.json']},'windows':records,'limitations':['IdealOSC excludes oscillator power; vm_osc is only1TΩdummy.','RTL and XSPICE output sources do not model digital-cell switching power.','Behavioral fitted GATE/FAULT pads do not qualify realpadpower; externalbehavioralload is separate.','Supplynetwork is idealboardrails+0.5ohm+1nF perrail; no assembledPDN/return/packageRC.','One nominal27Ctrajectory and programmedstate, not PVT/mismatch or worstcase activity.','Sampled peaks and numericalintegration may miss highfrequency energy; no independent transient convergence study.','Do not sum with standaloneBGR/SENSE/GATE evidence as though independent additionalblocks.']}
(a.output/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
for r in records:print(r['window'],json.dumps(r['blocks']), 'TOTAL',r['named_analog_rail_power_W']+r['named_digital_rail_power_W'])
